blogblog:
    resource: "@blogblogBundle/Controller/"
    type:     annotation
    prefix:   /
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
blogblogBundle_about:
    path:   /about
    defaults: { _controller: "blogblogBundle:Default:about" }
    requirements:
         methods:  GET
blogblogBundle_contact:
    path:  /contact
    defaults: { _controller: "blogblogBundle:Default:contact" }
    requirements:
        methods:  GET|POST
blogblogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: "blogblogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+
blogblogBundle_registration:
    path:   /registration
    defaults: { _controller: "blogblogBundle:Default:registration" }
    requirements:
blogblogBundle_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: "blogblogBundle:Comment:create" }
    requirements:
        methods:  POST
        blog_id: \d+